//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartTrackingWebApplicationMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcalar
    {
        public int parcaId { get; set; }
        public string parcaIsmi { get; set; }
        public string parcaDurumu { get; set; }
        public Nullable<int> isPersonelId { get; set; }
        public Nullable<System.DateTime> iletilenTarih { get; set; }
        public Nullable<System.DateTime> yapilanTarih { get; set; }
        public Nullable<int> parcaDurumId { get; set; }
    
        public virtual Durumlar Durumlar { get; set; }
        public virtual Personeller Personeller { get; set; }
    }
}
